name: Build and push Docker images for all components

on:
  push:
    branches: [ "main" ]
    paths:
    - package.json
    - src/**
  pull_request:
    branches: [ "main" ]
    paths:
    - package.json
    - src/**
  workflow_dispatch: {}

env:
  DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
  IMAGE_PREFIX: eclipseaerios
  IMAGE_NAME: benchmarking-tool

jobs:
  build-and-push-all:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ env.DOCKER_HUB_USER }}
        password: ${{ env.DOCKER_HUB_TOKEN }}

    - name: Set short SHA
      id: shortsha
      run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

    - name: Find all Dockerfiles
      id: find_dockerfiles
      run: |
        find . -name 'Dockerfile' > dockerfiles.txt
        cat dockerfiles.txt

    - name: Get version from package.json
      id: get_version
      run: echo "VERSION=$(jq -r .version package.json)" >> "$GITHUB_OUTPUT"

    - name: Build and push images for all Dockerfiles (amd64)
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        while read dockerfile; do
          dir=$(dirname "$dockerfile")
          image="${{ env.IMAGE_PREFIX }}/${{env.IMAGE_NAME}}"
          echo "Building $image for amd64 from $dockerfile"
          docker buildx build \
            --platform linux/amd64 \
            --file "$dockerfile" \
            --push \
            --tag "$image:latest-amd64" \
            --tag "$image:${{ steps.shortsha.outputs.SHORT_SHA }}-amd64" \
            --tag "$image:${{ steps.get_version.outputs.VERSION }}-amd64" \
            "$dir"
        done < dockerfiles.txt

    - name: Build and push images for all Dockerfiles (arm64)
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        while read dockerfile; do
          dir=$(dirname "$dockerfile")
          image="${{ env.IMAGE_PREFIX }}/${{env.IMAGE_NAME}}"
          echo "Building $image for arm64 from $dockerfile"
          docker buildx build \
            --platform linux/arm64 \
            --file "$dockerfile" \
            --push \
            --tag "$image:latest-arm64" \
            --tag "$image:${{ steps.shortsha.outputs.SHORT_SHA }}-arm64" \
            --tag "$image:${{ steps.get_version.outputs.VERSION }}-arm64" \
            "$dir"
        done < dockerfiles.txt